"""add staged analysis tables

Revision ID: c4c9aabbd8d9
Revises:
Create Date: 2026-07-02 08:23:16.708925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4c9aabbd8d9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: this was originally autogenerated and picked up a large amount of
    unrelated schema drift -- drops of legacy Prisma-era tables ("User",
    "Analysis", "Account", "Session", "Payment", "transactions", etc.) that
    still hold real data ("User" and "Account" each have live rows), plus
    NOT NULL / foreign-key changes on the current analyses/users tables.
    All of that has been stripped out. This migration now does ONLY what it
    was meant to do: add the 4 staged-analysis tables.
    """
    op.create_table(
        "analysis_basic_summary",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("total_income", sa.Float(), nullable=True),
        sa.Column("total_expenses", sa.Float(), nullable=True),
        sa.Column("net_cash_flow", sa.Float(), nullable=True),
        sa.Column("average_balance", sa.Float(), nullable=True),
        sa.Column("savings_rate", sa.Float(), nullable=True),
        sa.Column("burn_rate_daily", sa.Float(), nullable=True),
        sa.Column("total_fees", sa.Float(), nullable=True),
        sa.Column("fee_pct", sa.Float(), nullable=True),
        sa.Column("fuliza_total", sa.Float(), nullable=True),
        sa.Column("fuliza_count", sa.Integer(), nullable=True),
        sa.Column("betting_total", sa.Float(), nullable=True),
        sa.Column("betting_pct", sa.Float(), nullable=True),
        sa.Column("p2p_total", sa.Float(), nullable=True),
        sa.Column("p2p_count", sa.Integer(), nullable=True),
        sa.Column("highest_transaction", sa.Float(), nullable=True),
        sa.Column("highest_transaction_date", sa.String(), nullable=True),
        sa.Column("total_transactions", sa.Integer(), nullable=True),
        sa.Column("transaction_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_basic_summary_analysis_id"),
        "analysis_basic_summary",
        ["analysis_id"],
        unique=True,
    )

    op.create_table(
        "analysis_behavior_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("health_score", sa.Integer(), nullable=True),
        sa.Column(
            "health_breakdown", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "fuliza_cycles", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "income_analysis", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "day_of_week_spend", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("salary_day", sa.Integer(), nullable=True),
        sa.Column(
            "recurring_payments", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("anomalies", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_behavior_metrics_analysis_id"),
        "analysis_behavior_metrics",
        ["analysis_id"],
        unique=True,
    )

    op.create_table(
        "analysis_category_breakdown",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column(
            "category_data", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "monthly_data", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("trend_data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "top_depositors", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "top_creditors", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("top_category", sa.String(), nullable=True),
        sa.Column("top_category_amount", sa.Float(), nullable=True),
        sa.Column("top_category_percent", sa.Float(), nullable=True),
        sa.Column("top_income_source", sa.String(), nullable=True),
        sa.Column("income_concentration", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_category_breakdown_analysis_id"),
        "analysis_category_breakdown",
        ["analysis_id"],
        unique=True,
    )

    op.create_table(
        "analysis_insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("insights", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("warnings", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "recommendations", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("income_change", sa.Float(), nullable=True),
        sa.Column("expenses_change", sa.Float(), nullable=True),
        sa.Column("ai_enriched", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_insights_analysis_id"),
        "analysis_insights",
        ["analysis_id"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f("ix_analysis_insights_analysis_id"), table_name="analysis_insights"
    )
    op.drop_table("analysis_insights")

    op.drop_index(
        op.f("ix_analysis_category_breakdown_analysis_id"),
        table_name="analysis_category_breakdown",
    )
    op.drop_table("analysis_category_breakdown")

    op.drop_index(
        op.f("ix_analysis_behavior_metrics_analysis_id"),
        table_name="analysis_behavior_metrics",
    )
    op.drop_table("analysis_behavior_metrics")

    op.drop_index(
        op.f("ix_analysis_basic_summary_analysis_id"),
        table_name="analysis_basic_summary",
    )
    op.drop_table("analysis_basic_summary")